import type { Metadata } from 'next';
import Navbar from '@/components/Navbar/Navbar';
import { Toaster } from '@/components/ui/toaster';
import Chatbot from '@/components/Chatbot';

// Styles
import './globals.css';
// Font
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'AI Retail Demo',
  description: 'Generated by Rivat Technologies Co.,Ltd',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Chatbot />
        <Toaster />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
